### PR TITLE
Switch Encode to take &mut E

### LINKED ISSUE #459: ICE: `thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0'`
See: https://github.com/kdy1/wasm-perf/pull/1

I filed [an issue on rust issue tracker](https://github.com/rust-lang/rust/issues/92470), but I think it can be workarounded for now.

Stack:

```

query stack during panic:
#0 [codegen_fulfill_obligation] checking if `bincode::config::internal::InternalIntEncodingConfig` fulfil
ls its obligations
#1 [resolve_instance] resolving instance `<_ as bincode::config::internal::InternalIntEncodingConfig>::IN
T_ENCODING`
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #459

### CODE REVIEW

File: derive/src/derive_enum.rs [hunk 1]
```diff
@@ -29,7 +29,7 @@ impl DeriveEnum {
             .generate_fn("encode")
             .with_generic("E", ["bincode::enc::Encoder"])
             .with_self_arg(FnSelfArg::RefSelf)
-            .with_arg("mut encoder", "E")
+            .with_arg("mut encoder", "&mut E")
```
Comment (VictorKoenders) [inline derive/src/derive_enum.rs]: This can be `"encoder"`

**Review by VictorKoenders — APPROVED** [review]
